NEEDED_COLUMNS = [
    ('Player Details', 'Rk'),
    ('Player Details', 'Player'),
    ('Player Details', 'Nation'),
    ('Player Details', 'Pos'),
    ('Player Details', 'Squad'),
    ('Player Details', 'Age'),
    ('Playing Time', 'MP'),
    ('Playing Time', 'Starts'),
    ('Playing Time', 'Min'),
    ('Playing Time', '90s'),
    ('Performance', 'Gls'),
    ('Performance', 'Ast'),
    ('Performance', 'G-PK'),
    ('Performance', 'CrdY'),
    ('Performance', 'CrdR'),
    ('Expected', 'xG'),
    ('Expected', 'npxG'),
    ('Expected', 'xAG'),
    ('Progression', 'PrgC'),
    ('Progression', 'PrgP'),
    ('Per 90 Minutes', 'Gls'),
    ('Per 90 Minutes', 'Ast'),
    ('Per 90 Minutes', 'xG'),
    ('Per 90 Minutes', 'xAG'),
]
CLUBS_COLUMN_MAPPING = {
    "squad": "name",
    "xg": "xG",
    "xga": "xGA",
    "last_5": "last_five",
    "gf": "goals_scored",
    "ga": "goals_conceded",
    "gd": "goal_difference",
    "xgd": "xGD",
    "pts": "points",
    "mp": "matches_played",
    "w": "wins",
    "d": "draws",
    "l": "losses",
    "prgc": "prgC",
    "prgp": "prgP",
    "#_pl": "no_players",
    "age": "average_age",
    "attendance": "attendance_per_game",
    "xgdp90": "xGDp90",
    "xgp90": "xGp90",
    "poss": "possession",
    "rk": "position",
    "ptspmp": 'ppg',
}

PLAYERS_COLUMN_MAPPING = {
    'player': 'name',
    'nation': 'nationality',
    'pos': 'position',
    'mp': 'matches_played',
    'crdr': 'red_cards',
    'crdy': 'yellow_cards',
    'starts': 'starts',
    '90s': 'full_90s',
    'min': 'minutes',
    'gls': 'goals',
    'ast': 'assists',
    'g-pk': 'non_penalty_goals',
    'xg': 'xG',
    'npxg': 'npxG',
    'xag': 'xAG',
    'prgc': 'prgC',
    'prgp': 'prgP',
    'glsp90': 'goals_p90',
    'astp90': 'assists_p90',
    'xgp90': 'xG_p90',
    'xagp90': 'xAG_p90',
    'tkl': 'tackles',
    'saves': 'saves',
    'cs': 'clean_sheets',
    'blocks': 'blocks',
    'save%': 'save_percent',
    'is_captain': 'is_captain',
    'clr': 'clearances',
    'int': 'interceptions',
}


column_maps = NEEDED_COLUMNS, CLUBS_COLUMN_MAPPING, PLAYERS_COLUMN_MAPPING
